---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: package.json
  label: theme config
  match: "**/*"
- type: document
  path: dist/contact.html
  label: contact
  match: "**/*"
- type: document
  path: dist/work.html
  label: work
  match: "**/*"
- type: document
  path: dist/about.html
  label: about
  match: "**/*"
- type: document
  path: dist/index.html
  label: index
  match: "**/*"
- type: directory
  path: dist
  label: Projects
  create: documents
  match: "**/*.md"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
